
# basic makefile
#
# Which c compiler
CC = g++

# compiler options
CFLAGS = -std=c++11

# target executable
TARGET = virtual

all:
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).cpp constants.cpp
clean:
	rm virtual
